@startuml

' http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.githubusercontent.com/kwk/llvm-ci/trybot-setup/deployment.puml&fmt=svg

!include <office/Concepts/firewall.puml>
!include <office/Devices/device_laptop.puml>
!include <office/Security/key_permissions_green.puml>
!include <office/Security/key_permissions.puml>
!include <office/Security/lock_protected_blue.puml>
!include <office/Security/lock_protected.puml>
!include <office/Security/lock_with_key_security_blue.puml>
!include <office/Security/lock_with_key_security_green.puml>
!include <office/Security/lock_with_key_security_orange.puml>
!include <office/Users/users_blue.puml>
!include <office/Users/users.puml>

!include <tupadr3/common>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/github>

' Used to center the label under the images
skinparam defaultTextAlignment center
skinparam shadowing false

skinparam rectangle {
    roundCorner<<Concept>> 54
}

title Deployment Diagram for llvm-ci

actor "Alice" as alice

rectangle "OpenShift on Product and Tools Shared Infrastructure (PSI) Cluster" <<Concept>>  {
  rectangle "llvm-pre-merge namespace" as namespace {
    database "<$key_permissions_green>\nWorker secrets" as worker_secret {
    }
    database "<$key_permissions_green>\nGithub self-hosted\nactions-runner Token" as runner_secret {
    }
    rectangle "master-pod" as master_pod {
      rectangle "master-container" {
        database "SQLite" {
        }
      }
    }
    rectangle "worker-pod" as worker_pod {
      rectangle "worker-container"
    }
    rectangle "runner-pod" as runner_pod {
      rectangle "runner-container" {
        (actions-runner client) as actions_runner_client
      }
    }
    interface "Buildbot UI\n(HTTP[s])" as master_www_service
  }

  rectangle "<$firewall>\nFirewall" as firewall {
  }

}

cloud "Internet" as internet {
}

cloud "Red Hat VPN" as vpn {
}

rectangle "<$github>\n kwk/llvm-ci-demo repo" as github {
  rectangle "Buildbot Secret" as github_secret {
  }
}

control "Run Github Action\n(on self-hosted runner\nbut only for this demo because\nbuildbot master is behind a firewall)" as github_actions

master_www_service - master_pod

alice -down-> github : "PR Comment: /build-on"

github -down-> github_actions

github_secret .. github_actions : "pass along secret\nto runner"

github_actions -0)- internet  : "Webhooks"

internet - vpn

vpn - firewall

firewall -down- actions_runner_client : "self-register and\nlisten to webhook"

worker_secret -0)- worker_pod

runner_secret -0)- runner_pod

@enduml