version: "3.8"
services:

    # The buildbot master
    master:
        container_name: master-container
        user: johndoe:root
        build:
            context: ./master
        ports:
            # Port to Try-Scheduler
            - "8031:8031"
            # Prometheus exporter (visit http://localhost:9101/metrics)
            - "9101:9101"
            # Web Frontend
            - "8010:8010"
        # Only workers must reach the workers-port,
        # hence we only expose but not publish it on the host.
        expose:
            # Workers Port
            - "9989"
        volumes:
            - "./master/cfg:/home/johndoe/cfg:Z"
            - "./master/compose-secrets/:/secret-volume/:Z"
        environment:
            BUILDBOT_MASTER_TITLE: "Compose"
            BUILDBOT_MASTER_TRY_PORT: "8031"
            BUILDBOT_MASTER_PORT: "9989"
            BUILDBOT_WWW_PORT: "8010"
            BUILDBOT_WWW_URL: https://localhost:8443/
        networks:
            - master
            - worker
        healthcheck:
            test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8010"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # This acts as the SSL reverse proxy to buildbot
    reverse-proxy:
        container_name: reverse_proxy
        image: nginx:1.19
        volumes:
            - "./reverse-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:Z"
            - "./reverse-proxy/certs:/certs:Z"
        ports:
            - "8443:8443"
            # - "8080:8080"
        depends_on:
            - master
        networks:
            - master
            - worker

    # Spawn 3 buildbot workers one after another
    worker0:
        container_name: worker-container0
        build: ./worker
        environment:
            BUILDBOT_WORKER_NAME: worker0
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: master:9989
        networks:
            - worker
        depends_on:
            - master
        volumes:
          - "./worker/compose-secrets:/secret-volume:Z"
    
    worker1:
        container_name: worker-container1
        build: ./worker
        environment:
            BUILDBOT_WORKER_NAME: worker1
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: master:9989
        networks:
            - worker
        depends_on:
            - worker0
        volumes:
          - "./worker/compose-secrets:/secret-volume:Z"

    worker2:
        container_name: worker-container2
        build: ./worker
        environment:
            BUILDBOT_WORKER_NAME: worker2
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: master:9989
        networks:
            - worker
        depends_on:
            - worker1
        volumes:
          - "./worker/compose-secrets:/secret-volume:Z"

    # Github self-hosted actions-runner
    runner:
        container_name: runner-container
        # TODO(kwk): Sadly I haven't figured out a way to get rid of this because the
        # github actions runner binary requires quite some permissions when it upgrades it self.
        # This self-upgrade cannot be stopped. 
        user: johndoe:root
        build: ./runner
        environment:
            # These two variables are diven by the .env file which is generated by "make prepare-secrets"
            GH_OWNER: ${GH_OWNER}
            GH_REPO: ${GH_REPO}
        networks:
            - master
        depends_on:
            - master
            - worker1
            - worker2
        volumes:
          - "./runner/compose-secrets:/secret-volume:Z"

networks:
    master:
    worker: