apiVersion: v1
kind: Pod
metadata:
  name: runner-pod
  labels:
    os: "fedora"
    os_version: "33"
    arch: "x86_64"
    app: "buildbot"
    tier: "runner"
spec:
  containers:
    - name: runner-container
      image: "${RUNNER_IMAGE}"
      command: ["/home/runner/start-runner.sh"]
      resources:
        limits:
          memory: "3Gi" # e.g. 64 Gigabytes = 64 Gi
          cpu: "10000m" # e.g. 32 cores = 32000m
      volumeMounts:
        - name: runner-secret-volume
          mountPath: /runner-secret-volume
          readOnly: true
      env:
        - name: GH_OWNER
          value: "kwk"
        - name: GH_REPO
          value: "llvm-ci-demo"
  volumes:
    - name: runner-secret-volume
      secret:
        secretName: runner-secret