# give-tips-on-new-pr.yml

name: 'Give Tips on a PR'
description: 'Creates a comment on a PR to tell about the possibilites to engage in a conversation with the CI system.'
inputs:
  pr-number:
    description: 'The PR to comment on'
    required: true
    default: ''
  pr-author:
    description: 'Who to greet'
    required: true
    default: github.event.pull_request.user.login
  buildbot-web-url:
    description: 'URL to buildbot page'
    required: true
    default: 'http://localhost:8010/#/builders'

runs:
  steps:
    - uses: actions/github-script@v3
      with:
        # GitHub provides a token that you can use to authenticate on behalf of GitHub Actions.
        # See https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: ${{ inputs.pr-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you @${{ inputs.pr-author }} for opening this Pull Request!

            This message was automatically generated to help you understand how you
            can engage in a conversation with the CI system backing this repository.

            Please issue a comment like `/build-on <builder>`, where `<builder>` is a buildbot
            builder name.
            
            You can find a list of all builders on [this local Buildbot page](${{ inputs.buildbot-web-url }}).`
          })