# For a documentation on the meaning of each field in this file see:
# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions

name: Give Tips on a PR
author: Konrad Kleine
description: |
  Creates a comment on a PR to tell about the possibilites
  to engage in a conversation with the CI system.
inputs:
  pr-number:
    description: The PR to comment on
    required: true
    default: ''
  pr-author:
    description: Who to greet
    required: true
    default: github.event.pull_request.user.login
  buildbot-web-url:
    description: URL to buildbot page
    required: false
    default: 'http://localhost:8010/#/builders'
runs:
  using: node12
  main: index.js
          