@startuml

' http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.githubusercontent.com/kwk/llvm-ci/trybot-setup/deployment.puml&fmt=svg

!include <office/Concepts/firewall.puml>

' Used to center the label under the images
skinparam defaultTextAlignment center
skinparam shadowing false
skinparam Padding 10
skinparam DefaultFontName "DejaVu Sans"
skinparam DefaultFontSize 30

title Simplified dataflow when browsing buildbot's web frontend\n(all items marked with a * will be created for you)

actor "Alice" as alice

rectangle "Kubernetes or OpenShift Cluster" {
  frame "your namespace or project" as namespace {
       
    rectangle "master-pod*" as master_pod {
      rectangle "master-container*" as master_container {
        database "SQLite*" as sqllite
        note right of sqllite : We don't bother too much\nwhich the DB and instead use\nwhatever is deployed easily.
    
        rectangle buildbot [
          Buildbot Master*
          ....
          Configured with master.cfg file
          that is baked into the container
          image
        ]
        interface "port*" as master_www_port
        note left of master_www_port : Buildbot UI port (8010 TCP/IP)
      }
    }
    interface "service*      " as master_www_service
    note right of master_www_service : Buildbot UI Service\nexposed through a route

    rectangle master_secret [
      <&key*1> Secrets
      ----
      worker names
      worker password
      ----
      try names
      try passwords
    ]
    note right of master_secret : Secrets from either master/k8s/secret.yaml.sample\nor master/k8s/secret.yaml (preferred if it exists)
  }
  rectangle "<$firewall>\nFirewall" as firewall
}

cloud "Internet" as internet {
}

cloud "Your VPN" as vpn {
}

alice - internet 

internet - vpn

vpn -down- firewall

firewall -right-( master_www_service

' master_www_service - master_pod

master_www_service -down-( master_www_port

master_www_port -right- buildbot

buildbot <-> sqllite

master_secret <-up- buildbot : consumes 


@enduml